trigger:
  branches:
    include:
      - main
      - development

pr:
  branches:
    include:
      - main
      - development

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_OPTS: -Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository

steps:
  - checkout: self
    fetchDepth: 0

  - task: SonarCloudPrepare@2
    displayName: Prepare SonarCloud analysis
    inputs:
      SonarCloud: 'SonarCloudServiceConnection'
      organization: 'x00229514'
      scannerMode: 'Other'
      configMode: 'manual'
      cliProjectKey: 'X00229514_task-tracker-api'
      cliProjectName: 'task-tracker-api'
      extraProperties: |
        sonar.java.binaries=$(System.DefaultWorkingDirectory)/target/classes
        sonar.coverage.jacoco.xmlReportPaths=$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml

  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: maven | "$(Agent.OS)" | pom.xml
      path: $(Pipeline.Workspace)/.m2/repository

  - task: JavaToolInstaller@0
    displayName: Use JDK 21
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: mvn -B verify sonar:sonar
    displayName: Build, test, coverage, static analysis

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@2
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/jacoco.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/site/jacoco'
      failIfCoverageEmpty: true
    condition: succeededOrFailed()

  - task: SonarCloudPublish@2
    displayName: Publish SonarCloud quality gate
    inputs:
      pollingTimeoutSec: '300'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: Publish SpotBugs report
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target/spotbugsXml.xml'
      ArtifactName: 'spotbugs-report'
      publishLocation: 'Container'
    condition: succeededOrFailed()
