trigger:
  branches:
    include:
      - main
      - development

pr:
  branches:
    include:
      - main
      - development

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_OPTS: -Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository

steps:
  - checkout: self
    fetchDepth: 0

  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: maven | "$(Agent.OS)" | pom.xml
      path: $(Pipeline.Workspace)/.m2/repository

  - task: UseJavaVersion@1
    inputs:
      versionSpec: '21'
      architecture: 'x64'

  - script: mvn -B verify
    displayName: Build, test, coverage, static analysis

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/jacoco.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/site/jacoco'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: Publish SpotBugs report
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target/spotbugsXml.xml'
      ArtifactName: 'spotbugs-report'
      publishLocation: 'Container'
    condition: succeededOrFailed()
